---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  environments_path: 'test/environments'
  client_rb:
    environment: 'kitchen'
  ssl_verify_mode: :verify_none
  verify_api_cert: false
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: bento/centos-7.3
  - name: windows-2012r2-chef-12.6
    driver_config:
      box: chef/windows-server-2012r2-standard
    transport:
      name: winrm

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[jenkins_swarm::swarm_client]
    attributes:
